#!/usr/bin/env bash

function main {
  mkdir -p ~/.terraform.d/plugin-cache

  local exts="vscodevim.vim tamasfe.even-better-toml jnoortheen.nix-ide hashicorp.terraform golang.go esbenp.prettier-vscode bazelbuild.vscode-bazel cuelang.cue pbkit.vscode-pbkit marp-team.marp-vscode tailscale.vscode-tailscale geequlim.godot-tools alfish.godot-files ms-pyright.pyright ms-python.python"

  (
    code --list-extensions
    for a in 1 2; do for b in $exts; do echo "$b"; done; done
  ) | tr A-Z a-z | sort | uniq -c | grep ' 2 ' | while read -r count extension; do
    case "$(uname -s)-${extension}" in
      Darwin-cuelang.cue)
        true
        ;;
      *)
        if $(which code code-server | head -1) serve-local --force --install-extension "${extension}"; then
          true
        fi
        ;;
    esac
  done
}

main "$@"
