#!/usr/bin/env bash

function main {
    mkdir -p ~/.aws
    ln -nfs ../.password-store/defn/aws/aws-config.txt ~/.aws/config

    mkdir -p ~/.ssh
    case "$(uname -s)" in
        Linux)
            ln -nfs ../.dotfiles/etc/config ~/.ssh/
            ;;
        Darwin)
            ln -nfs ../.dotfiles/etc/authorized_keys ~/.ssh/
            ;;
    esac

    if ! test -d ~/.local/share/code-server/extensions/vscode-cue/.git; then
        git clone https://github.com/cue-sh/vscode-cue ~/.local/share/code-server/extensions/vscode-cue
    fi

    for a in vscodevim.vim matthewpi.caddyfile-support tamasfe.even-better-toml jnoortheen.nix-ide runem.lit-plugin svelte.svelte-vscode hashicorp.terraform golang.Go; do
        $(which code code-server | head -1) --install-extension "$a"
    done
}

main "$@"
