#!/usr/bin/env bash

function main {
    ln -nfs ../.password-store/defn/aws/aws-config.txt ~/.aws/config

    if ! test -d ~/.local/share/code-server/extensions/vscode-cue/.git; then
        git clone https://github.com/cue-sh/vscode-cue ~/.local/share/code-server/extensions/vscode-cue
    fi

    for a in vscodevim.vim matthewpi.caddyfile-support tamasfe.even-better-toml jnoortheen.nix-ide runem.lit-plugin svelte.svelte-vscode hashicorp.terraform golang.Go; do
        case "${VSCODE_GIT_ASKPASS_NODE:-}" in
            */code-server*)
                code-server --install-extension "$a"
                ;;
            *)
                code --install-extension "$a"
                ;;
        esac
    done
}

main "$@"
