build-site:
	cd app && earthly --push --no-output +buil32.1:5000/workspace:latest

manual-site:
	if test -f /run/secrets/kubernetes.io/serviceaccount/ca.crt; then \
		$(MAKE) vault-unseal; \
		aws --profile meh sts get-caller-identity; \
		$(MAKE) vault-seal; \
		fi
