build-site:
	cd app && docker build --no-cache -t 169.254.32.1:5000/workspace .
	docker push 169.254.32.1:5000/workspace

install-site:
	for a in matthewpi.caddyfile-support tamasfe.even-better-toml jnoortheen.nix-ide golang.Go vscodevim.vim runem.lit-plugin; do code-server --install-extension "$$a"; done;
