apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k3d-smiley-cert-manager
  namespace: argocd
spec:
  destination:
    name: k3d-smiley
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/cert-manager
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: k3d-smiley-demo2
  namespace: argocd
spec:
  destination:
    name: k3d-smiley
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/demo2
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-smiley-external-secrets-operator
  namespace: argocd
spec:
  destination:
    name: k3d-smiley
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/external-secrets-operator
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  name: k3d-smiley-kuma-zone
  namespace: argocd
spec:
  destination:
    name: k3d-smiley
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/k3d-smiley-kuma-zone
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k3d-smiley-kyverno
  namespace: argocd
spec:
  destination:
    name: k3d-smiley
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/kyverno
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: k3d-smiley-secrets-store
  namespace: argocd
spec:
  destination:
    name: k3d-smiley
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/k3d-smiley-secrets-store
    repoURL: https://github.com/defn/app
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
