# ManagedBy: cue

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: vcluster-control-vc2
spec:
  project: default
  destination:
    name: in-cluster
  source:
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
    path: k/vcluster-control-vc2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
