apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: vcluster-control-vc3-cert-manager
  namespace: argocd
spec:
  destination:
    name: vcluster-control-vc3
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/cert-manager
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
