#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev
spec:
  provider:
    vault:
      server: http://100.103.25.109:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: pod
          role: external-secrets
