#!/usr/bin/env bash

function main {
    set -exfu

    touch /tmp/cache-priv-key.pem
    chmod 600 /tmp/cache-priv-key.pem
    (set +x; echo "$NIX_CACHE_PRIV_KEY" > /tmp/cache-priv-key.pem)
    chmod 400 /tmp/cache-priv-key.pem

    touch /tmp/wh.log
    chmod 600 /tmp/wh.log

    sudo install -d -m 0755 -o ubuntu -g ubuntu /cache/nix

    caddy run &
    webhook --hooks gh.json --template --verbose &
    tail -f /tmp/wh.log &

    while [[ "000" == "$(curl -sS -o /dev/null -w "%{http_code}" --connect-timeout 1 -m 1 http://localhost:8001)" ]]; do sleep 1; done
    while [[ "000" == "$(curl -sS -o /dev/null -w "%{http_code}" --connect-timeout 1 -m 1 http://localhost:9000)" ]]; do sleep 1; done

    # then run tired-proxy
    exec tired-proxy --host http://localhost:8001 --port 8000 --time 300
}

main "$@"
