#!/usr/bin/env bash

function main {
    exec 2>>/tmp/meh.log

    (cd /; echo "${DEFN_DEV_ARCHIVE}" | base64 -d | tar xvf -)

    (setsid /usr/sbin/tailscaled --statedir=/var/lib/tailscale) &

    (sleep 5; tailscale up --ssh --hostname "$(echo "${DEFN_DEV_HOST}" | cut -d. -f1)") &

    while ! tailscale ip -4; do sleep 1; done

    (setsid sudo -u ubuntu -H ~ubuntu/bin/e kuma-cp-on) &

    (setsid sudo -u ubuntu -H ~ubuntu/bin/e kuma-ingress-on) &

    (setsid sudo -u ubuntu -H --preserve-env=PASSWORD ~ubuntu/bin/e code-server --bind-addr 0.0.0.0:8888 --disable-telemetry) &

    exec caddy run
}

main "$@"

#exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o StreamLocalBindUnlink=yes
