#!/usr/bin/env bash

function main {
    exec 2>>/tmp/meh.log

    (cd /; echo "${DEFN_DEV_ARCHIVE}" | base64 -d | tar xvf -)

    dd if=/dev/zero of=/root/swap0 bs=1M count=200
    chmod 0600 /root/swap0
    mkswap /root/swap0
    swapon /root/swap0

    (setsid /usr/sbin/tailscaled --statedir=/var/lib/tailscale) &

    (sleep 5; tailscale up --ssh --hostname "$(echo "${DEFN_DEV_HOST}" | cut -d. -f1)") &

    while ! tailscale ip -4; do sleep 1; done

    (setsid dockerd --mtu="$(ifconfig eth0 | grep mtu | awk '{print $NF}')") & 

    export DOCKER_HOST=unix:///var/run/docker.sock
    while ! docker ps; do sleep 1; done

    docker run --rm -d -p 7777:80 containous/whoami    

    (setsid bash -c "while true; do sudo -u ubuntu -H ~ubuntu/bin/e kuma-cp-on; sleep 5; done") &

    (setsid bash -c "while true; do sudo -u ubuntu -H ~ubuntu/bin/e kuma-ingress-on; sleep 5; done") &

    (setsid bash -c "while true; do sudo -u ubuntu -H ~ubuntu/bin/e kuma-dp-on; sleep 5; done") &

    (setsid bash -c "while true; do sudo -u ubuntu -H --preserve-env=PASSWORD ~ubuntu/bin/e code-server --bind-addr 0.0.0.0:8888 --disable-telemetry; sleep 5; done") &

    exec caddy run
}

main "$@"

#exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o StreamLocalBindUnlink=yes
